feat/ lecture card component
WavetexDev/wds-core pull request #4
Opened 2023-07-01 19:20 UTC by gustavoZuin237

This branch includes:
* Lecture Card component
* Story for said component

2023-07-03 23:57 UTC, zuinl requested changes
Aplicar correções solicitadas e analisar sugestões

2023-07-03 23:57 UTC, zuinl commented on src/components/course-banner/index.tsx
> +import { Typography } from '@waveclass/wds-core';
Como você está importante um componente da própria `wds-core`, é desnecessário possuir o pacote instalado. Nesse caso, importe localmente mesmo: `import { Typography } from '../../Typography'`

Com isso, ajuste todos os outros casos semelhantes e remova o `@waveclass/wds-core` do package.json

2023-07-03 23:57 UTC, zuinl commented on src/components/course-banner/styles.ts
> +	border-radius: 10px;
use `theme[currentMode].spacing.sp10`

2023-07-03 23:57 UTC, zuinl commented on src/components/course-banner/styles.ts
> +	padding: 0
Na verdade pode deixar o `padding` geral para todos os lados. Verifique qual se encaixa melhor, se `14px` ou `18px`

2023-07-03 23:57 UTC, zuinl commented on src/components/course-banner/styles.ts
> +		url(${banner})`
Mudar para: `url('${banner}')`. Quando a URL da imagem possuir algum caractere especial, isso quebra no browser, causando erro no carregamento da imagem, por isso é indicado o uso das aspas simples

2023-07-03 23:57 UTC, zuinl commented on src/components/course-banner/types.ts
> +export interface CourseBannerProps {
Adicione mais duas props (obrigatórias): `courseId` e `onClick`. O `onClick` deve ser uma `function(courseId: string) => void` e deve ser invocado quando o usuário clicar no Course Banner, enviando `courseID` como argumento.

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/types.ts
> +	cardVariant: CardVariant;
Deixe apenas `variant` para fins de padronização e torne esta prop opcional. Quando não informada, assuma  que é `secondary` por padrão.

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/types.ts
> +type Lecture = 'video' | 'audio' | 'material' | 'text';
Boa! Mas apenas para fim de padronização com os dados que usamos na Waveclass, deixe as opções assim: `VIDEO | AUD | MAT | TEXT`

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/types.ts
> +	author: string;
Altere para `teacher`

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/types.ts
> +	lectureType: Lecture;
Deixe apenas `type`

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/types.ts
> +	title: string;
Alterar para `name`

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/types.ts
> +	pillVariant: PillVariant;
Remova `pillVariant` e `pillText` das props. Essas informações serão construídas internamente pelo próprio componente

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/types.ts
> +export interface LectureCardProps {
Adicione estas props: `finished` (boolean, opcional), `progress` (number, opcional. É a quantidade de segundos já assistidos), `onClick` (function => void), `available` (boolean, indica se uma aula pode ser assistida), `favorite` (boolean, opcional)

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/index.tsx
Precisamos adicionar um ícone de indicação de aula favorita. Alinhe comigo após aplicar os demais ajustes

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/styles.ts
> +	border-radius: 8px;
Use o `spacing` do theme

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/styles.ts
> +			? `url(${thumbnail})`
Usar `url('${thumbnail}')`

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/styles.ts
> +export const LectureTitle = styled.main<LectureCardStyleProps>`
Hmmmm... deu uma pesquisada se é indicado usar `main` e `footer` em cenários como esse? Acredito que dentro de um componente não seja muito indicado. Defenda essa abordagem por favor

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/index.tsx
> +	function formatClassDuration(duration: number) {
Transforme esta função em um utilitário na pasta utils do projeto, com nome sugerido de `secondsToFriendlyString`

2023-07-03 23:57 UTC, zuinl commented on src/components/lecture-card/index.tsx
> +	function determineLectureTypeIcon(lectureType: string) {
Você não precisa receber `lectureType` por parâmetro aqui, você já tem ele disponível da sua `props`.

2023-07-03 23:57 UTC, zuinl commented on src/components/pill/styles.ts
> +	return variant.includes('outline')
Eu fortemente recomendo utilizar `switch` _case_ ao invés desse grande bloco `if` neste caso.

Exemplo

```
if(variant.includes('outline') return 'transparent';

switch(variant) {
  ...your cases
}
```

2023-07-03 23:57 UTC, zuinl commented on stories/lecture-card/lecture-card.stories.tsx
Sugestão: fazer 1 Story pra cada tipo de aula

2023-07-04 17:11 UTC, gustavoZuin237 commented on stories/lecture-card/lecture-card.stories.tsx
Bom, cada tipo se difere dos outros apenas por um ícone diferente, e com os controles do Storybook podemos alternar fácil e rapidamente entre tipos de aula, o que altera o ícone mostrado em tela. Seria realmente necessário fazer uma Story para cada variação?

2023-07-04 17:11 UTC, gustavoZuin237 commented on src/components/lecture-card/index.tsx
Ok, vamos alinhar isso.

2023-07-05 15:03 UTC, zuinl requested changes
Aplicar atualizações solicitadas

2023-07-05 15:03 UTC, zuinl commented on src/components/lecture-card/index.tsx
Adicione as seções de mensagem quando a aula não estiver disponível e o ícone de favorito, conforme atualizado no Figma.

2023-07-05 15:03 UTC, zuinl commented on src/components/lecture-card/types.ts
>  export interface LectureCardProps {
Adicione a prop: `toggleFavorite: () => void` que deverá ser chamada quando o usuário clicar sobre o ícone de favorito

2023-07-05 16:30 UTC, gustavoZuin237 commented on src/components/pill/styles.ts
> +		? `theme[currentMode].colors.white`
Certo, acho que fiz confusão na hora kkkk

2023-07-05 19:08 UTC, zuinl requested changes
Corrigir callback de onClick e adicionar ícone de favorito

2023-07-05 19:08 UTC, zuinl commented on src/components/lecture-card/index.tsx
> +			console.log('A aula está disponível!'); // TODO
chamar o `onClick` da prop

2023-07-05 19:08 UTC, zuinl commented on src/components/lecture-card/index.tsx
> +							''
Pode user `null`

2023-07-11 12:12 UTC, zuinl approved these changes

2023-07-11 12:12 UTC, merged